"""Internal helpers for :class:`StealthTransfer`.

Holds the state-accumulation dataclass, instruction emission, and
fee-binding logic. Split out of ``transfer.py`` so both files stay
under the project's 200-line ceiling.

The :class:`StealthTransferState` carrier mirrors the Rust
``StealthTransferSpec`` (``crates/wallet/ootle-rs/src/stealth/builder.rs:255``):
the resource being moved, an ordered map of stealth inputs to spend,
an accumulator for any revealed input amount, the ordered list of
stealth outputs, and an accumulator for any revealed output amount.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import TYPE_CHECKING

from ootle._types.instructions import InstructionArgWorkspace, StealthTransferInstruction
from ootle._types.substate import SubstateId
from ootle._types.want_input import WantInput
from ootle.errors import InvalidArgumentError

if TYPE_CHECKING:
    from ootle._sync.builders._base import WantInputItem
    from ootle._transaction_builder import TransactionBuilder
    from ootle._types.address import Address, ComponentAddress, ResourceAddress
    from ootle._types.instructions import WorkspaceOffsetId
    from ootle._types.stealth import Output, StealthInput, StealthTransferStatement


@dataclass(slots=True)
class StealthTransferState:
    """Accumulator mirroring Rust ``StealthTransferSpec``."""

    resource: ResourceAddress
    inputs_to_spend: dict[Address, StealthInput] = field(
        default_factory=dict["Address", "StealthInput"]
    )
    revealed_input_amount: int = 0
    outputs: list[Output] = field(default_factory=list["Output"])
    revealed_output_amount: int = 0
    fee_from_revealed: bool = False

    def total_output_amount(self) -> int:
        """Sum of stealth output amounts plus the revealed output bucket."""
        return sum(o.amount for o in self.outputs) + self.revealed_output_amount

    def total_input_amount(self) -> int:
        """Revealed input amount (stealth contributions are amount-hidden)."""
        return self.revealed_input_amount

    def is_balanced(self) -> bool:
        """Cheap pre-flight: revealed in + (hidden) outputs equal revealed out + stealth in.

        Stealth input/output amounts are commitment-hidden — only the
        revealed buckets can be balance-checked client-side. The full
        balance proof is generated by the stealth crypto provider.
        """
        # We cannot verify the hidden balance Python-side; the provider's
        # ``validate_transfer`` is authoritative. Return ``False`` only
        # when the revealed sides clearly disagree *and* there are no
        # stealth pieces to absorb the difference.
        if self.inputs_to_spend or self.outputs:
            return True
        return self.revealed_input_amount == self.revealed_output_amount


def ensure_positive(amount: int, *, label: str) -> int:
    """Validate ``amount`` is a positive int (mirrors Rust ``Amount::is_positive``)."""
    if amount <= 0:
        msg = f"{label} must be positive, got {amount}"
        raise InvalidArgumentError(msg)
    return amount


def add_stealth_input_want(
    want_list: set[WantInputItem],
    commitment: bytes,
    resource: ResourceAddress,
) -> None:
    """Register a stealth-commitment input on the builder's want-list."""
    want_list.add(WantInput.StealthCommitment(commitment=commitment, resource=resource))


def emit_stealth_transfer_instruction(
    builder: TransactionBuilder,
    resource: ResourceAddress,
    statement: StealthTransferStatement,
    revealed_input_bucket: WorkspaceOffsetId | None,
) -> None:
    """Append a single :class:`StealthTransferInstruction` to the body."""
    builder.add_instruction(
        StealthTransferInstruction(
            resource=resource,
            statement=statement,
            revealed_input_bucket=revealed_input_bucket,
        )
    )


def emit_revealed_output_deposit(
    builder: TransactionBuilder,
    want_list: set[WantInputItem],
    account: ComponentAddress,
    resource: ResourceAddress,
) -> None:
    """Deposit the stealth transfer's revealed-output bucket into ``account``.

    The :class:`StealthTransferInstruction` leaves a revealed-output
    bucket as its last output; capturing it on the workspace and calling
    ``Account::deposit`` consumes it. Without this the bucket dangles and
    the engine aborts the transaction.
    """
    label = "__StealthRevealedDeposit"
    builder.put_last_instruction_output_on_workspace(label)
    offset = builder._resolve_workspace_offset(label)  # pyright: ignore[reportPrivateUsage]  # internal access
    builder.call_method(account, "deposit", (InstructionArgWorkspace(offset),))
    want_list.add(WantInput.SpecificSubstate(id=SubstateId(opaque=str(account))))
    want_list.add(WantInput.VaultForResource(component=account, resource=resource, required=False))


def validate_state(state: StealthTransferState) -> None:
    """Pre-flight invariants enforced before the stealth crypto round-trip."""
    has_input = state.revealed_input_amount > 0 or bool(state.inputs_to_spend)
    has_output = state.revealed_output_amount > 0 or bool(state.outputs)
    if not has_input:
        msg = "stealth transfer requires at least one input (stealth or revealed)"
        raise InvalidArgumentError(msg)
    if not has_output:
        msg = "stealth transfer requires at least one output (stealth or revealed)"
        raise InvalidArgumentError(msg)


def collect_input_signers(
    state: StealthTransferState,
) -> tuple[tuple[Address, bytes], ...]:
    """Return a stable ``(spender, commitment)`` sequence for signer derivation.

    Mirrors the Rust iteration order in ``builder.rs::prepare`` — the
    ``IndexMap`` preserves insertion order, and so do Python ``dict``s.
    """
    return tuple((addr, inp.commitment) for addr, inp in state.inputs_to_spend.items())
