"""Shared helpers for async-suite tests.

Imported by the unit + integration tests under ``tests/_async/``. Has a
sync mirror generated by ``unasync`` so the same helpers are available
to ``tests/_sync/``.
"""

from __future__ import annotations


def network_response(epoch: int = 1) -> dict[str, object]:
    """Canonical ``GET network`` mock body for ``Network.LOCAL_NET``."""
    return {"network": "localnet", "network_byte": 0x10, "epoch": epoch}
