"""``TransactionWatcher`` — multiplexed ``/events`` SSE subscription (sync).

Hand-written sync counterpart of
:class:`ootle._async._watcher._actor.AsyncTransactionWatcher`. Same
behaviour, but a daemon worker thread reads the stream and a
:class:`threading.Lock` guards the per-transaction
:class:`concurrent.futures.Future` registry. See that module's docstring
for why this package is hand-maintained rather than generated by
``unasync``.
"""

from __future__ import annotations

import contextlib
import logging
import threading
import time
from concurrent.futures import Future
from typing import TYPE_CHECKING

from httpx_sse import connect_sse as _open_sse_stream

from ootle._types._sse_events import FINALIZED_EVENT_TYPE, parse_finalized_event

if TYPE_CHECKING:
    import httpx
    from httpx_sse import EventSource, ServerSentEvent

    from ootle._types.transaction import TransactionId

logger = logging.getLogger(__name__)

_EVENTS_PATH = "/events"
_RECONNECT_DELAY = 1.0
"""Seconds to wait before re-subscribing after the ``/events`` stream drops."""


class TransactionWatcher:
    """Background subscriber that resolves per-transaction finalisation futures.

    Created and started by :meth:`IndexerTransport.transaction_watcher`;
    callers interact with it only indirectly via
    :class:`~ootle._sync._watcher._pending.PendingTransaction`.
    """

    __slots__ = (
        "_client",
        "_connect_error",
        "_connected",
        "_events_url",
        "_lock",
        "_registry",
        "_running",
        "_source",
        "_thread",
    )

    def __init__(self, client: httpx.Client, base_url: str) -> None:
        self._client = client
        self._events_url = f"{base_url.rstrip('/')}{_EVENTS_PATH}"
        self._registry: dict[TransactionId, Future[str | None]] = {}
        self._lock = threading.Lock()
        self._thread: threading.Thread | None = None
        self._connected = threading.Event()
        self._connect_error: BaseException | None = None
        self._source: EventSource | None = None
        self._running = False

    def start(self) -> None:
        """Subscribe to ``/events`` and block until the stream is live.

        Idempotent. Raises whatever the first subscription attempt raised
        if it failed — the caller is expected to fall back to REST polling.
        """
        if self._thread is not None:
            return
        self._connected = threading.Event()
        self._connect_error = None
        self._running = True
        thread = threading.Thread(target=self._run, name="ootle-tx-watcher", daemon=True)
        self._thread = thread
        thread.start()
        self._connected.wait()
        if self._connect_error is not None:
            error = self._connect_error
            self.close()
            raise error

    def register(self, tx_id: TransactionId) -> Future[str | None]:
        """Return a future resolved with the ``outcome`` tag when *tx_id* finalises."""
        with self._lock:
            existing = self._registry.get(tx_id)
            if existing is not None and not existing.done():
                return existing
            future: Future[str | None] = Future()
            self._registry[tx_id] = future
            return future

    def unregister(self, tx_id: TransactionId) -> None:
        """Drop the registration for *tx_id* (the caller stopped waiting)."""
        with self._lock:
            self._registry.pop(tx_id, None)

    def close(self) -> None:
        """Stop the subscriber and settle any outstanding futures."""
        self._running = False
        source, self._source = self._source, None
        if source is not None:
            with contextlib.suppress(Exception):
                source.response.close()
        thread, self._thread = self._thread, None
        if thread is not None and thread.is_alive():
            thread.join(timeout=_RECONNECT_DELAY)
        self._settle_outstanding()

    def _run(self) -> None:
        first_attempt = True
        try:
            while self._running:
                try:
                    with _open_sse_stream(self._client, "GET", self._events_url) as source:
                        self._source = source
                        first_attempt = False
                        self._connected.set()
                        logger.debug("transaction watcher: subscribed to /events")
                        for sse in source.iter_sse():
                            if not self._running:
                                break
                            self._dispatch(sse)
                except Exception as exc:  # keep the watcher alive across any /events fault
                    if first_attempt:
                        self._connect_error = exc
                        self._connected.set()
                        return
                    if self._running:
                        logger.warning(
                            "transaction watcher: /events fault (%s); reconnecting in %ss",
                            exc,
                            _RECONNECT_DELAY,
                        )
                else:
                    if self._running:
                        logger.info(
                            "transaction watcher: /events closed by indexer; reconnecting in %ss",
                            _RECONNECT_DELAY,
                        )
                finally:
                    self._source = None
                if not self._running:
                    break
                time.sleep(_RECONNECT_DELAY)
        finally:
            self._settle_outstanding()

    def _dispatch(self, sse: ServerSentEvent) -> None:
        if sse.event != FINALIZED_EVENT_TYPE:
            return
        parsed = parse_finalized_event(sse.data)
        if parsed is None:
            return
        tx_id, outcome_tag = parsed
        with self._lock:
            future = self._registry.pop(tx_id, None)
        if future is None or future.done():
            return
        logger.debug("transaction watcher: %s finalised (outcome=%s)", tx_id, outcome_tag)
        future.set_result(outcome_tag)

    def _settle_outstanding(self) -> None:
        with self._lock:
            registry, self._registry = self._registry, {}
        for future in registry.values():
            if not future.done():
                future.cancel()
